"""Constants for the Haier AC Bridge integration."""

from __future__ import annotations

from homeassistant.const import Platform

DOMAIN = "haier_ac_bridge"

PLATFORMS: list[Platform] = [Platform.CLIMATE, Platform.SWITCH]

CONF_POLLING = "polling"
CONF_USE_FAN_MODE = "use_fan_mode"
CONF_USE_DRY_MODE = "use_dry_mode"
CONF_HEALTH_MODE_TYPE = "health_mode_type"
CONF_SWING_TYPE = "swing_type"
CONF_ACDEVICE_NAME = "acdevice_name"
CONF_ACDEVICE_FAN_RIGHTLEFT = "acdevice_fan_rightleft"
CONF_ACDEVICE_FAN_UPDOWN = "acdevice_fan_updown"
CONF_ACDEVICE_HEALTHMODE = "acdevice_healthmode"
CONF_ACDEVICE_DRYMODE = "acdevice_drymode"

HEALTH_MODE_SHOW = "SHOW"
HEALTH_MODE_FORCE = "FORCE"
HEALTH_MODE_OFF = "OFF"
HEALTH_MODE_TYPES = [HEALTH_MODE_SHOW, HEALTH_MODE_FORCE, HEALTH_MODE_OFF]

SWING_TYPE_BOTH = "BOTH"
SWING_TYPE_INDIVIDUAL = "INDIVIDUAL"
SWING_TYPE_OFF = "OFF"
SWING_TYPES = [SWING_TYPE_INDIVIDUAL, SWING_TYPE_BOTH, SWING_TYPE_OFF]

DEFAULT_POLLING_SECONDS = 5
DEFAULT_USE_FAN_MODE = True
DEFAULT_USE_DRY_MODE = True
DEFAULT_HEALTH_MODE_TYPE = HEALTH_MODE_SHOW
DEFAULT_SWING_TYPE = SWING_TYPE_INDIVIDUAL
DEFAULT_ACDEVICE_NAME = "AC"
DEFAULT_ACDEVICE_FAN_RIGHTLEFT = "RightLeft Swing"
DEFAULT_ACDEVICE_FAN_UPDOWN = "UpDown Swing"
DEFAULT_ACDEVICE_HEALTHMODE = "Health Mode"
DEFAULT_ACDEVICE_DRYMODE = "Dry Mode"

OPTION_DEFAULTS: dict[str, object] = {
    CONF_POLLING: DEFAULT_POLLING_SECONDS,
    CONF_USE_FAN_MODE: DEFAULT_USE_FAN_MODE,
    CONF_USE_DRY_MODE: DEFAULT_USE_DRY_MODE,
    CONF_HEALTH_MODE_TYPE: DEFAULT_HEALTH_MODE_TYPE,
    CONF_SWING_TYPE: DEFAULT_SWING_TYPE,
    CONF_ACDEVICE_NAME: DEFAULT_ACDEVICE_NAME,
    CONF_ACDEVICE_FAN_RIGHTLEFT: DEFAULT_ACDEVICE_FAN_RIGHTLEFT,
    CONF_ACDEVICE_FAN_UPDOWN: DEFAULT_ACDEVICE_FAN_UPDOWN,
    CONF_ACDEVICE_HEALTHMODE: DEFAULT_ACDEVICE_HEALTHMODE,
    CONF_ACDEVICE_DRYMODE: DEFAULT_ACDEVICE_DRYMODE,
}

DEVICE_MODE_COOL = "COOL"
DEVICE_MODE_HEAT = "HEAT"
DEVICE_MODE_SMART = "SMART"
DEVICE_MODE_FAN = "FAN"
DEVICE_MODE_DRY = "DRY"

DEVICE_FAN_LOW = "LOW"
DEVICE_FAN_MID = "MID"
DEVICE_FAN_HIGH = "HIGH"
DEVICE_FAN_AUTO = "AUTO"

MIN_TEMP = 16
MAX_TEMP = 30
