"""Constants for the Haier AC Bridge integration."""

from __future__ import annotations

from typing import Any, Final

from homeassistant.const import Platform

DOMAIN: Final = "haier_ac_bridge"

PLATFORMS: Final[list[Platform]] = [Platform.CLIMATE, Platform.SWITCH]

CONF_CONNECTION_TYPE: Final = "connection_type"
CONF_POLLING: Final = "polling"
CONF_MAC: Final = "mac"
CONF_USE_FAN_MODE: Final = "use_fan_mode"
CONF_USE_DRY_MODE: Final = "use_dry_mode"
CONF_HEALTH_MODE_TYPE: Final = "health_mode_type"
CONF_SWING_TYPE: Final = "swing_type"
CONF_ACDEVICE_NAME: Final = "acdevice_name"
CONF_ACDEVICE_FAN_RIGHTLEFT: Final = "acdevice_fan_rightleft"
CONF_ACDEVICE_FAN_UPDOWN: Final = "acdevice_fan_updown"
CONF_ACDEVICE_HEALTHMODE: Final = "acdevice_healthmode"
CONF_ACDEVICE_DRYMODE: Final = "acdevice_drymode"

CONNECTION_TYPE_BRIDGE: Final = "bridge"
CONNECTION_TYPE_DIRECT: Final = "direct"
CONNECTION_TYPES: Final = [CONNECTION_TYPE_BRIDGE, CONNECTION_TYPE_DIRECT]

HEALTH_MODE_SHOW: Final = "SHOW"
HEALTH_MODE_FORCE: Final = "FORCE"
HEALTH_MODE_OFF: Final = "OFF"
HEALTH_MODE_TYPES: Final = [HEALTH_MODE_SHOW, HEALTH_MODE_FORCE, HEALTH_MODE_OFF]

SWING_TYPE_BOTH: Final = "BOTH"
SWING_TYPE_INDIVIDUAL: Final = "INDIVIDUAL"
SWING_TYPE_OFF: Final = "OFF"
SWING_TYPES: Final = [SWING_TYPE_INDIVIDUAL, SWING_TYPE_BOTH, SWING_TYPE_OFF]

DEFAULT_POLLING_SECONDS: Final = 5
MIN_POLLING_SECONDS: Final = 1
MAX_POLLING_SECONDS: Final = 300
DEFAULT_USE_FAN_MODE: Final = True
DEFAULT_USE_DRY_MODE: Final = True
DEFAULT_HEALTH_MODE_TYPE: Final = HEALTH_MODE_SHOW
DEFAULT_SWING_TYPE: Final = SWING_TYPE_INDIVIDUAL
DEFAULT_ACDEVICE_NAME: Final = "AC"
DEFAULT_ACDEVICE_FAN_RIGHTLEFT: Final = "RightLeft Swing"
DEFAULT_ACDEVICE_FAN_UPDOWN: Final = "UpDown Swing"
DEFAULT_ACDEVICE_HEALTHMODE: Final = "Health Mode"
DEFAULT_ACDEVICE_DRYMODE: Final = "Dry Mode"

OPTION_DEFAULTS: Final[dict[str, Any]] = {
    CONF_POLLING: DEFAULT_POLLING_SECONDS,
    CONF_USE_FAN_MODE: DEFAULT_USE_FAN_MODE,
    CONF_USE_DRY_MODE: DEFAULT_USE_DRY_MODE,
    CONF_HEALTH_MODE_TYPE: DEFAULT_HEALTH_MODE_TYPE,
    CONF_SWING_TYPE: DEFAULT_SWING_TYPE,
    CONF_ACDEVICE_NAME: DEFAULT_ACDEVICE_NAME,
    CONF_ACDEVICE_FAN_RIGHTLEFT: DEFAULT_ACDEVICE_FAN_RIGHTLEFT,
    CONF_ACDEVICE_FAN_UPDOWN: DEFAULT_ACDEVICE_FAN_UPDOWN,
    CONF_ACDEVICE_HEALTHMODE: DEFAULT_ACDEVICE_HEALTHMODE,
    CONF_ACDEVICE_DRYMODE: DEFAULT_ACDEVICE_DRYMODE,
}

DEVICE_MODE_COOL: Final = "COOL"
DEVICE_MODE_HEAT: Final = "HEAT"
DEVICE_MODE_SMART: Final = "SMART"
DEVICE_MODE_FAN: Final = "FAN"
DEVICE_MODE_DRY: Final = "DRY"

DEVICE_MODES: Final = [
    DEVICE_MODE_COOL,
    DEVICE_MODE_HEAT,
    DEVICE_MODE_SMART,
    DEVICE_MODE_FAN,
    DEVICE_MODE_DRY,
]

DEVICE_FAN_LOW: Final = "LOW"
DEVICE_FAN_MID: Final = "MID"
DEVICE_FAN_HIGH: Final = "HIGH"
DEVICE_FAN_AUTO: Final = "AUTO"

DEVICE_FAN_SPEEDS: Final = [
    DEVICE_FAN_LOW,
    DEVICE_FAN_MID,
    DEVICE_FAN_HIGH,
    DEVICE_FAN_AUTO,
]

MIN_TEMP: Final = 16
MAX_TEMP: Final = 30

# Ports and network timeouts shared by the API clients.
BRIDGE_PORT: Final = 10000
BRIDGE_TIMEOUT: Final = 10.0
DIRECT_PORT: Final = 56800
DIRECT_TIMEOUT: Final = 5.0

# Delay before re-reading the device after a command, so the AC has time to
# apply it and the optimistic state gets confirmed by a real poll.
COMMAND_REFRESH_DELAY: Final = 2.0
